### PR TITLE
Added direct support for Shelly Gen2+ devices

### PR DESCRIPTION
**Pull request by jjdejong**
It was somewhat awkward to have to use something like Node-RED to map the Shelly MQTT data to the format required by the original driver. So I coded a direct support for my Shelly devices.

### CODE REVIEW

**Comment by mr-manuel** [comment]
Why are you not using https://github.com/victronenergy/dbus-shelly/?

**Comment by jjdejong** [comment]
> Why are you not using https://github.com/victronenergy/dbus-shelly/?

Only supports the very specific Shelly Pro EM devices that use a totally different JSON payload. I tried to adapt that, but didn't succeed.

**Comment by jjdejong** [comment]
By the way, this code also merges some reformatting from a 0.18 fork that wasn't in the main branch.

**Comment by mr-manuel** [comment]
Thank you for your contribution. I simplified the integration a bit, so no extra config is needed.

**Comment by jjdejong** [comment]
> Thank you for your contribution. I simplified the integration a bit, so no extra config is needed.

Cool, by detecting "apower" in the JSON payload ;-)

**Pull request closed without merging**
